version: '3.4'

services:
    nginx:
        volumes:
            - ./build/public:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

secrets:
    nginx.crt:
        file: .nginx.crt
    nginx.key:
        file: .nginx.key
