version: '3.4'

services:
    nginx:
        image: eu.gcr.io/docker-223614/blog_nginx:latest
        build: .
        ports:
            - '80'
            - '443'
        secrets:
            - nginx.crt
            - nginx.key

secrets:
    nginx.crt:
        external: true
    nginx.key:
        external: true
